In [2]:
import numpy as numpy____library_____imported 
def Fuzzy_______operation____method(variable___vector___x, variable___vector__a, variable___vector__y, variable___vector__b, op):
    variable___yy, variable___xx = numpy____library_____imported.meshgrid(variable___vector__y, variable___vector___x, sparse=True)
    variable___bb, variable___aa = numpy____library_____imported.meshgrid(variable___vector__b, variable___vector__a, sparse=True)
    variable___zz = op(variable___xx, variable___yy).ravel()
    zz_index = numpy____library_____imported.argsort(variable___zz)
    variable___zz = numpy____library_____imported.sort(variable___zz)
    variable___c = numpy____library_____imported.fmin(variable___aa, variable___bb).ravel()
    variable___c = variable___c[zz_index]
    z, variable___mfz = numpy____library_____imported.zeros(0), numpy____library_____imported.zeros(0)
    idx = 0

    for _ in range(len(variable___c)):
        index = numpy____library_____imported.nonzero(variable___zz == variable___zz[idx])[0]
        z = numpy____library_____imported.hstack((z, variable___zz[idx]))
        variable___mfz = numpy____library_____imported.hstack((variable___mfz, variable___c[index].max()))
        idx = index[-1] + 1
        if idx >= len(variable___zz):
            break
    return z, variable___mfz


def fuzzy_____addition(variable___vector___x, variable___vector__a, variable___vector__y, variable___vector__b):
    return Fuzzy_______operation____method(variable___vector___x, variable___vector__a, variable___vector__y, variable___vector__b, op=numpy____library_____imported.add)


def fuzzy______division(variable___vector___x, variable___vector__a, variable___vector__y, variable___vector__b):
    if numpy____library_____imported.all(numpy____library_____imported.asarray(variable___vector__y) == 0):
        Warning('The 0 value(s) will never be used in the calculation!')
    index = numpy____library_____imported.where(variable___vector__y == 0)[0]
    numpy____library_____imported.delete(variable___vector__y, index)
    numpy____library_____imported.delete(variable___vector__b, index)
    return Fuzzy_______operation____method(variable___vector___x, variable___vector__a, variable___vector__y, variable___vector__b, op=numpy____library_____imported.divide)

def fuzzy_mult(variable___vector___x, variable___vector__a, variable___vector__y, variable___vector__b):
    return Fuzzy_______operation____method(variable___vector___x, variable___vector__a, variable___vector__y, variable___vector__b, op=numpy____library_____imported.multiply)


def fuzzy_sub(variable___vector___x, variable___vector__a, variable___vector__y, variable___vector__b):
    return Fuzzy_______operation____method(variable___vector___x, variable___vector__a, variable___vector__y, variable___vector__b, op=numpy____library_____imported.subtract)


variable___vector___x=[11,22,33,44]
variable___vector__a=[7,7,7,7]
variable___vector__y=[21,41,51,61]
variable___vector__b=[25,35,35,25]

variable___k1=fuzzy_____addition(variable___vector___x,variable___vector__a,variable___vector__y,variable___vector__b)
print("Fuzzy Addition Operation Output")
print(variable___k1)
variable___k2=fuzzy_sub(variable___vector___x,variable___vector__a,variable___vector__y,variable___vector__b)
print("Fuzzy Substraction  Operation Output")
print(variable___k2)
print("Fuzzy Multiplication Operation Output")
variable___k3=fuzzy_mult(variable___vector___x,variable___vector__a,variable___vector__y,variable___vector__b)
print(variable___k3)
print("Division")
r4=fuzzy______division(variable___vector___x,variable___vector__a,variable___vector__y,variable___vector__b)
print(r4)

Fuzzy Addition Operation Output
(array([ 32.,  43.,  52.,  54.,  62.,  63.,  65.,  72.,  73.,  74.,  83.,
        84.,  85.,  94.,  95., 105.]), array([7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]))
Fuzzy Substraction  Operation Output
(array([-50., -40., -39., -30., -29., -28., -19., -18., -17., -10.,  -8.,
        -7.,   1.,   3.,  12.,  23.]), array([7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]))
Fuzzy Multiplication Operation Output
(array([ 231.,  451.,  462.,  561.,  671.,  693.,  902.,  924., 1122.,
       1342., 1353., 1683., 1804., 2013., 2244., 2684.]), array([7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]))
Division
(array([0.18032787, 0.21568627, 0.26829268, 0.36065574, 0.43137255,
       0.52380952, 0.53658537, 0.54098361, 0.64705882, 0.72131148,
       0.80487805, 0.8627451 , 1.04761905, 1.07317073, 1.57142857,
       2.0952381 ]), array([7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]))
